server:
  port: 8081

spring:
  application:
    name: filestorage-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sems?currentSchema=fs_schema
    username: postgres
    password: root
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
app:
  scheduling:
    cron:
      outdated-files: "0 0 0 1 1/1 *"
  file-outdate-year: 15
  upload-directory: /tmp/filestorage/


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    status-page-url-path: /actuator/health
    prefer-ip-address: true


