server:
  port: 8081

spring:
  application:
    name: filestorage-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sems?currentSchema=fs_schema
    username: postgres
    password: root
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka-server/eureka


